/*
 * LauncherPanel.java
 *
 * Created on 2 November 2007, 21:48
 */

package launcherfd;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Properties;

/**
 *
 * @author  aulaskar
 */
public class LauncherPanel extends javax.swing.JPanel {
    
    /** Creates new form LauncherPanel */
    public LauncherPanel(String conffile) {
        initComponents();
        
        Properties props = new Properties();
        try {
            FileInputStream in = new FileInputStream( conffile );
            props.load(in);
        } catch (FileNotFoundException fe) {
            System.err.println("Missing " + conffile + " -file!");
            System.exit(-1);
        } catch (IOException ie) {
            System.err.println("Reading " + conffile + " failed!");
            System.exit(-1);        
        } catch (Exception e) {
            System.err.println("Reading properties failed \n" + e);
            System.exit(-1);
        }
        
        timeout = Integer.parseInt(props.getProperty("timeout", "10000"));
        jLabel1.setText(props.getProperty("title", "Application launcher"));
        jLabel2.setText(props.getProperty("launch", "Launch applications"));
        jLabel3.setText(props.getProperty("leagues", "Leagues"));        
        
        workingDir = new File(props.getProperty("workingdir"));
        separator = props.getProperty("separator");
        extension = props.getProperty("extension");
        app1 = props.getProperty("app1");
        app2 = props.getProperty("app2");
        app3 = props.getProperty("app3");
        app4 = props.getProperty("app4");
        
        String app1name = props.getProperty("app1name");
        String app2name = props.getProperty("app2name");
        String app3name = props.getProperty("app3name");
        String app4name = props.getProperty("app4name");
        
        if(app1name != null) {
            jCheckBox1.setText(app1name);
            jCheckBox1.setSelected(true);
        }
        if(app2name != null) {
            jCheckBox2.setText(app2name);
            jCheckBox2.setSelected(true);
        }
        if(app3name != null) {
            jCheckBox3.setText(app3name);
            jCheckBox3.setSelected(true);
        }
        if(app4name != null) {
            jCheckBox4.setText(app4name);
            jCheckBox4.setSelected(true);
        }
            
        String league1 = props.getProperty("league1");
        String league2 = props.getProperty("league2");
        String league3 = props.getProperty("league3");
        String league4 = props.getProperty("league4");
        String league5 = props.getProperty("league5");
              
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { league1, league2, league3, league4, league5 }));
        jLabel4.setText(props.getProperty("startall"));
        jButton1.setText(props.getProperty("confirm"));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox4 = new javax.swing.JCheckBox();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Choose applications");

        jLabel3.setText("League");

        jCheckBox1.setText("jCheckBox1");
        jCheckBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jCheckBox2.setText("jCheckBox2");
        jCheckBox2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox2.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jCheckBox3.setText("jCheckBox3");
        jCheckBox3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox3.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jButton1.setText("OK");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel4.setText("Launch applications");

        jCheckBox4.setText("jCheckBox4");
        jCheckBox4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox4.setMargin(new java.awt.Insets(0, 0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jCheckBox1)
                                    .addComponent(jCheckBox2)
                                    .addComponent(jCheckBox3)
                                    .addComponent(jLabel2)
                                    .addComponent(jCheckBox4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox1)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox2)
                        .addGap(16, 16, 16)
                        .addComponent(jCheckBox3)
                        .addGap(15, 15, 15)
                        .addComponent(jCheckBox4)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(229, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    /** Pressing ok makes selected programs launch */
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
        SimpleDateFormat df = new SimpleDateFormat("yyyyMMdd");
        String fileNameBase = 
                System.getProperty("file.separator") + jComboBox1.getSelectedItem().toString() + separator + df.format(new Date());
        System.out.println("Filename " + fileNameBase);        
        
        try {
            
            //inherit env from this launcher, 
            //be in the correct working dir first!
            //
            //text editor:
            if(jCheckBox1.isSelected()) {
                Runtime.getRuntime().exec(app1 + " "+ workingDir + fileNameBase + ".txt", null, workingDir);                
            }
            //mp3 player:
            if(jCheckBox2.isSelected()) {
                Thread.sleep(timeout);                
                Runtime.getRuntime().exec(app2, null, workingDir);
            }
            //Peli.jar:
            if(jCheckBox3.isSelected()) {
                Thread.sleep(timeout);
                Runtime.getRuntime().exec(app3 + " "+ workingDir + fileNameBase + ".tnmt", null, workingDir);
            }
            //Irc-bot:
            if(jCheckBox4.isSelected()) {
                Thread.sleep(timeout);
                //precreate file so ircbot will work, should be non-destructive
                new File(workingDir + fileNameBase + ".txt").createNewFile();
                new File(workingDir + fileNameBase + ".tnmt").createNewFile();
                Runtime.getRuntime().exec(app4 + " "+ workingDir + fileNameBase + ".tnmt", null, workingDir);            
            }
        } catch (Exception e) {
            System.err.println("Problem while launching an application:");
            e.printStackTrace();            
        }
        
        System.exit(0);
    }//GEN-LAST:event_jButton1MouseClicked
        
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
   
    private int timeout;
    private File workingDir;
    private String separator;
    private String extension;
    private String app1;
    private String app2;
    private String app3;
    private String app4;
    
    
  
}

